<a href="https://colab.research.google.com/github/jdansb/The-Quantum-Foundations-Project/blob/main/exemplo_incompatibilidade.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
# @title
import numpy as np
np.set_printoptions(suppress=True, precision=2)

print("Vamos considerar o operador A:")
A = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 2]
])
print(A)
print("\nPara verificar que é uma matriz hermitiana, podemos verificar seu transposto conjugado:")
m=A.T
m=m.conj()
print(m)

autovalores, autovetores = np.linalg.eig(A)
print("\nSeus autovalores são:")
print(autovalores)

print("\nE os correspondentes autovetores (cada coluna é um autovetor) são")
print(autovetores)


print("\nTemos então que o autovalor 1 é degenerado. Podemos reconstruir a matriz A pela decomposição espectral:")
av1=autovetores[:, 0].reshape(-1, 1)
av2=autovetores[:, 1].reshape(-1, 1)
av3=autovetores[:, 2].reshape(-1, 1)
m=autovalores[0]*av1@av1.T+autovalores[1]*av2@av2.T+autovalores[2]*av3@av3.T
print(m)

print("\nDefinimos agora uma matriz hermitiana B:")
B = np.array([
    [3, 1, 0],
    [1, 4, 0],
    [0, 0, 5]
])
print(B)
print("\nPodemos verificar que eles comutam, isto é, AB-BA=0:")
print(A@B-B@A)

print("\nemos então um subespaço de apenas uma dimensão para o autovalor 2. Podemos conferir que Bv=bv, sendo b=5")
v=B@av3
print(v)

print("\nAgora para o autovalor 1, temos um subespaço de duas dimensões formada pelos vetores")
print(autovetores[:, :2])

print("\nAplicando B ao primeiro autovetor, podemos ver que ele é uma combinação linear dos outros 2 autovetores do espaço:")
v=B@av1
print(v)

print("Ou seja, ainda que esses dois autovetores associados a 1 sejam uma base para esse subespaço, eles não formam uma base de autovetores comum. Mas podemos construir uma.")
print("\n Neste espaço bidimensional, atuação de B sobre os vetores do espaço é dada apenas por:")
B2 = np.array([
    [3, 1],
    [1, 4]])
print(B2)

autovaloresB2, autovetoresB2 = np.linalg.eig(B2)
print("\nSeus autovalores são")
print(autovaloresB2)

print("\nE os correspondentes autovetores (cada coluna é um autovetor) são:")
print(autovetoresB2)

print("\nPodemos então diagonalizar B nessa nova base:")
m=B2@autovetoresB2
m=autovetoresB2.T.conj()@m
print(m)
print("\nAgora temos o bloco de B associado ao autovalor 1 de A. Combinando-o com o bloco associado ao autovalor 2, obtemos na nova base:")
BD = np.array([
    [2.38196601, 0, 0],
    [0, 4.61803399, 0],
    [0, 0, 5]
])
print(BD)
autovaloresBD, autovetoresBD = np.linalg.eig(BD)

print("\nA nova base é dada pelos vetores (onde cada coluna corresponde a um vetor da nova base):")
base = np.array([[-0.85065081,-0.52573111,0],
 [ 0.52573111,-0.85065081,0],
                 [ 0,0,1],])
print(base)

print("\nReescrevendo A nesta base, ele se mantém inalterado:")
m=A@base
m=base.T.conj()@m
print(m)

print("\nEntão esta é a base de autovetores comuns a A e B")


Vamos considerar o operador A:
[[1 0 0]
 [0 1 0]
 [0 0 2]]

Para verificar que é uma matriz hermitiana, podemos verificar seu transposto conjugado:
[[1 0 0]
 [0 1 0]
 [0 0 2]]

Seus autovalores são:
[1. 1. 2.]

E os correspondentes autovetores (cada coluna é um autovetor) são
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Temos então que o autovalor 1 é degenerado. Podemos reconstruir a matriz A pela decomposição espectral:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]

Definimos agora uma matriz hermitiana B:
[[3 1 0]
 [1 4 0]
 [0 0 5]]

Podemos verificar que eles comutam, isto é, AB-BA=0:
[[0 0 0]
 [0 0 0]
 [0 0 0]]

emos então um subespaço de apenas uma dimensão para o autovalor 2. Podemos conferir que Bv=bv, sendo b=5
[[0.]
 [0.]
 [5.]]

Agora para o autovalor 1, temos um subespaço de duas dimensões formada pelos vetores
[[1. 0.]
 [0. 1.]
 [0. 0.]]

Aplicando B ao primeiro autovetor, podemos ver que ele é uma combinação linear dos outros 2 autovetores do espaço:
[[3.]
 [1.]
 [0.]]
Ou seja, ainda que