<a href="https://colab.research.google.com/github/jdansb/The-Quantum-Foundations-Project/blob/main/exemplo_incompatibilidade.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [85]:
printa()

Vamos considerar o operador A:
[[1 0 0]
 [0 1 0]
 [0 0 2]]

Para verificar que é uma matriz hermitiana, podemos verificar seu transposto conjugado:
[[1 0 0]
 [0 1 0]
 [0 0 2]]

Seus autovalores são:
[1. 1. 2.]

E os correspondentes autovetores (cada coluna é um autovetor) são
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Temos então que o autovalor 1 é degenerado. Podemos reconstruir a matriz A pela decomposição espectral:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]

Definimos agora uma matriz hermitiana B:
[[3 1 0]
 [1 4 0]
 [0 0 5]]

Podemos verificar que eles comutam, isto é, AB-BA=0:
[[0 0 0]
 [0 0 0]
 [0 0 0]]

No caso mais simples, temos então um subespaço de apenas uma dimensão para o autovalor 2. Podemos conferir que Bv=bv, sendo b=5
[[0.]
 [0.]
 [5.]]

Agora para o autovalor 1, temos um subespaço de duas dimensões formada pelos vetores
[[1. 0.]
 [0. 1.]
 [0. 0.]]

Todos vetores não nulos neste subespaço continuam a serem autovetores de A com o mesmo autovalor.
Se denotamos os dois autovetore

In [84]:
def printa():
  import numpy as np
  np.set_printoptions(suppress=True, precision=2)

  print("Vamos considerar o operador A:")
  A = np.array([
      [1, 0, 0],
      [0, 1, 0],
      [0, 0, 2]
  ])
  print(A)
  print("\nPara verificar que é uma matriz hermitiana, podemos verificar seu transposto conjugado:")
  m=A.T
  m=m.conj()
  print(m)

  autovalores, autovetores = np.linalg.eig(A)
  print("\nSeus autovalores são:")
  print(autovalores)

  print("\nE os correspondentes autovetores (cada coluna é um autovetor) são")
  print(autovetores)


  print("\nTemos então que o autovalor 1 é degenerado. Podemos reconstruir a matriz A pela decomposição espectral:")
  av1=autovetores[:, 0].reshape(-1, 1)
  av2=autovetores[:, 1].reshape(-1, 1)
  av3=autovetores[:, 2].reshape(-1, 1)
  m=autovalores[0]*av1@av1.T+autovalores[1]*av2@av2.T+autovalores[2]*av3@av3.T
  print(m)

  print("\nDefinimos agora uma matriz hermitiana B:")
  B = np.array([
      [3, 1, 0],
      [1, 4, 0],
      [0, 0, 5]
  ])
  print(B)
  print("\nPodemos verificar que eles comutam, isto é, AB-BA=0:")
  print(A@B-B@A)

  print("\nNo caso mais simples, temos então um subespaço de apenas uma dimensão para o autovalor 2. Podemos conferir que Bv=bv, sendo b=5")
  v=B@av3
  print(v)

  print("\nAgora para o autovalor 1, temos um subespaço de duas dimensões formada pelos vetores")
  print(autovetores[:, :2])

  print("\nTodos vetores não nulos neste subespaço continuam a serem autovetores de A com o mesmo autovalor.")
  print("Se denotamos os dois autovetores calculados por (v1,v2) e utilzamos como base, qualquer autovetor que sejau ma combinação linear deles u=av1+bv2 então Au=aAv1+bAv2 =acv1+bcv2=c(av1+bv2)=cu.")
  print("Agora aplicando B ao primeiro autovetor, podemos ver que ele é uma combinação linear dos outros 2 autovetores do espaço e não é um autovetor de B:")
  v=B@av1
  print(v)

  print("Ou seja, ainda que esses dois autovetores associados a 1 sejam uma base para esse subespaço, eles não formam uma base de autovetores comum. Mas podemos construir uma.")
  print("Como todos vetores neste subespaço são autovetores de A, só precisamos encontrar aqueles que são também de B.")
  print("Neste espaço bidimensional, atuação de B sobre os vetores do espaço é dada apenas por:")
  B2 = np.array([
      [3, 1],
      [1, 4]])
  print(B2)

  autovaloresB2, autovetoresB2 = np.linalg.eig(B2)
  print("\nSeus autovalores são")
  print(autovaloresB2)

  print("\nE os correspondentes autovetores (cada coluna é um autovetor) são:")
  print(autovetoresB2)

  print("\nCombinando então com resultados anteriores, podemos ter nova base dada pelos autovetores comuns(onde cada coluna corresponde a um vetor da nova base):")
  base = np.array([[-0.85065081,-0.52573111,0],
  [ 0.52573111,-0.85065081,0],
                  [ 0,0,1],])
  print(base)
  autovaloresA, autovetoresA = np.linalg.eig(A)
  autovaloresB, autovetoresB = np.linalg.eig(B)
  av1=base[:, 0].reshape(-1, 1)
  av2=base[:, 1].reshape(-1, 1)
  av3=base[:, 2].reshape(-1, 1)
  print("Podemos testar aplicando A na base:")
  print(A@av1/autovaloresA[0])
  print(A@av2/autovaloresA[1])
  print(A@av3/autovaloresA[2])
  print("Onde dividimos cada vetor já pelo correspondente autovalor:")
  print(autovaloresA)
  print("Podemos testar aplicando B na base:")
  print(B@av1/autovaloresB[0])
  print(B@av2/autovaloresB[1])
  print(B@av3/autovaloresB[2])
  print("Onde dividimos cada vetor já pelo correspondente autovalor:")
  print(autovaloresB)


In [74]:
BD@av1

array([[2.38],
       [0.  ],
       [0.  ]])