<a href="https://colab.research.google.com/github/jdansb/The-Quantum-Foundations-Project/blob/main/exemplo_incompatibilidade.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

KeyboardInterrupt: 

In [2]:
import numpy as np

print("")
matrix1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Declarar a segunda matriz 3x3
matrix2 = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

print("Primeira Matriz:")
print(matrix1)

print("\nSegunda Matriz:")
print(matrix2)

Primeira Matriz:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Segunda Matriz:
[[9 8 7]
 [6 5 4]
 [3 2 1]]
